nome = input("Insira o nome do usuário: ")
idade = int(input("Insira a idade do usuário: "))
endereco = input("Insira o endereço do usuário: ")
estado_civil = input("Insira o estado civil do usuário: ")
escolaridade = input("Insira a escolaridade do usuário: ")
salario1 = float(input("Insira o primeiro salário do usuário: "))
salario2 = float(input("Insira o segundo salário do usuário: "))
salario3 = float(input("Insira o terceiro salário do usuário: "))

media_salario = (salario1+salario2+salario3)/3
dif_salario = abs(salario1-salario2)

print("\n\nNome do usuário",nome)
print("idade do usuário",idade)
print("endereço do usuário",endereco)
print("estado civil do usuário",estado_civil)
print("escolaridade do usuário",escolaridade)
print(f"primeiro salario do usuário R$ {salario1:.2f}")
print(f"segundo salario do usuário R$ {salario2:.2f}")
print(f"terceiro salario do usuário R$ {salario3:.2f}")
print(f"a sua média salaria é de: R${media_salario:.2f}")
print(f"a diferença entre o primeiro e o segundo salário é de: R${dif_salario:.2f}\n\n")